version: '3.4'

services:
  spellingbeekiller-game-server:
    image: ${DOCKER_REGISTRY-}mainapplication
    container_name: spellingbeekiller-game-server
    hostname: spellingbeekiller-game-server
    build:
      context: .
      dockerfile: MainApplication/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 # https://+:443; TODO get certificate for https
    ports:
      - "8081:80"
      # - "44301:443" TODO
    volumes:
      # TODO IDK what should be these, copied from bingo
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      
networks:
  default:
    external:
      name: SpellingBeeKillerGServices
      
