version: '3.4'

services:
  spellingbeekiller-game-server:
    image: spellingbeekiller:dev
    container_name: spellingbeekiller-game-server
    build:
      context: .
      dockerfile: Dockerfile  # Simplified path
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    networks:
      - default

networks:
  default:
    external:
      name: spellingbeekiller-gservices